/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial-basics',
      collapsed: false,
      items: ['tutorial-basics/congratulations', 'tutorial-basics/create-a-blog-post', 'tutorial-basics/create-a-document', 'tutorial-basics/create-a-page', 'tutorial-basics/deploy-your-site', 'tutorial-basics/live-coding']
    },
    {
      type: 'category',
      label: 'Tutorial-extras',
      collapsed: false,
      items: ['tutorial-extras/manage-docs-versions', 'tutorial-extras/translate-your-site'],
    },
    'design'
  ],
  design: [
    'antdesign',
    {
      type: 'category',
      label: 'Component',
      collapsed: false,
      items: ['Component/button']
    }
  ]

};

module.exports = sidebars;
